#!/bin/bash
### BEGIN INIT INFO
# Provides:             OracleXE
# Required-Start:       $remote_fs $syslog
# Required-Stop:        $remote_fs $syslog
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    Oracle 11g Express Edition
### END INIT INFO
